# Exported from Render on 2024-08-17T14:53:25Z
services:
  - type: web
    name: spotify-connected-app
    runtime: node
    repo: https://github.com/sarahschuller/spotify-connected-app
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    pullRequestPreviewsEnabled: false
version: "1"
